export const mapping = [{id: 2001, category: "GDP (purchasing power parity)"},
{id: 2002, category: "Population growth rate"},
{id: 2003, category: "GDP - real growth rate"},
{id: 2004, category: "GDP - per capita (PPP)"},
{id: 2005, category: "Affiliation"},
{id: 2006, category: "Dependency status"},
{id: 2007, category: "Diplomatic representation from the US"},
{id: 2008, category: "Transportation - note"},
{id: 2010, category: "Age structure"},
{id: 2011, category: "Geographic coordinates"},
{id: 2012, category: "GDP - composition, by sector of origin"},
{id: 2018, category: "Sex ratio"},
{id: 2019, category: "Heliports"},
{id: 2020, category: "Elevation extremes"},
{id: 2021, category: "Natural hazards"},
{id: 2022, category: "People - note"},
{id: 2023, category: "Area - comparative"},
{id: 2024, category: "Military service age and obligation"},
{id: 2025, category: "Manpower fit for military service"},
{id: 2026, category: "Manpower reaching militarily significant age annually"},
{id: 2028, category: "Background"},
{id: 2030, category: "Airports - with paved runways"},
{id: 2031, category: "Airports - with unpaved runways"},
{id: 2032, category: "Environment - current issues"},
{id: 2033, category: "Environment - international agreements"},
{id: 2034, category: "Military expenditures"},
{id: 2046, category: "Population below poverty line"},
{id: 2047, category: "Household income or consumption by percentage share"},
{id: 2048, category: "Labor force - by occupation"},
{id: 2049, category: "Exports - commodities"},
{id: 2050, category: "Exports - partners"},
{id: 2051, category: "Administrative divisions"},
{id: 2052, category: "Agriculture - products"},
{id: 2053, category: "Airports"},
{id: 2054, category: "Birth rate"},
{id: 2055, category: "Military branches"},
{id: 2056, category: "Budget"},
{id: 2057, category: "Capital"},
{id: 2058, category: "Imports - commodities"},
{id: 2059, category: "Climate"},
{id: 2060, category: "Coastline"},
{id: 2061, category: "Imports - partners"},
{id: 2063, category: "Constitution"},
{id: 2066, category: "Death rate"},
{id: 2068, category: "Dependent areas"},
{id: 2070, category: "Disputes - international"},
{id: 2075, category: "Ethnic groups"},
{id: 2076, category: "Exchange rates"},
{id: 2077, category: "Executive branch"},
{id: 2078, category: "Exports"},
{id: 2079, category: "Debt - external"},
{id: 2080, category: "Fiscal year"},
{id: 2081, category: "Flag description"},
{id: 2085, category: "Roadways"},
{id: 2086, category: "Illicit drugs"},
{id: 2087, category: "Imports"},
{id: 2088, category: "Independence"},
{id: 2089, category: "Industrial production growth rate"},
{id: 2090, category: "Industries"},
{id: 2091, category: "Infant mortality rate"},
{id: 2092, category: "Inflation rate (consumer prices)"},
{id: 2093, category: "Waterways"},
{id: 2094, category: "Judicial branch"},
{id: 2095, category: "Labor force"},
{id: 2096, category: "Land boundaries"},
{id: 2097, category: "Land use"},
{id: 2098, category: "Languages"},
{id: 2100, category: "Legal system"},
{id: 2101, category: "Legislative branch"},
{id: 2102, category: "Life expectancy at birth"},
{id: 2103, category: "Literacy"},
{id: 2105, category: "Manpower available for military service"},
{id: 2106, category: "Maritime claims"},
{id: 2107, category: "International organization participation"},
{id: 2108, category: "Merchant marine"},
{id: 2109, category: "National holiday"},
{id: 2110, category: "Nationality"},
{id: 2111, category: "Natural resources"},
{id: 2112, category: "Net migration rate"},
{id: 2113, category: "Geography - note"},
{id: 2115, category: "Political pressure groups and leaders"},
{id: 2116, category: "Economy - overview"},
{id: 2117, category: "Pipelines"},
{id: 2118, category: "Political parties and leaders"},
{id: 2119, category: "Population"},
{id: 2120, category: "Ports and terminals"},
{id: 2121, category: "Railways"},
{id: 2122, category: "Religions"},
{id: 2123, category: "Suffrage"},
{id: 2124, category: "Telephone system"},
{id: 2125, category: "Terrain"},
{id: 2127, category: "Total fertility rate"},
{id: 2128, category: "Government type"},
{id: 2129, category: "Unemployment rate"},
{id: 2137, category: "Military - note"},
{id: 2138, category: "Communications - note"},
{id: 2140, category: "Government - note"},
{id: 2141, category: "Group"},
{id: 2142, category: "Country name"},
{id: 2144, category: "Location"},
{id: 2145, category: "Map references"},
{id: 2146, category: "Irrigated land"},
{id: 2147, category: "Area"},
{id: 2149, category: "Diplomatic representation in the US"},
{id: 2150, category: "Telephones - main lines in use"},
{id: 2151, category: "Telephones - mobile cellular"},
{id: 2153, category: "Internet users"},
{id: 2154, category: "Internet country code"},
{id: 2155, category: "HIV/AIDS - adult prevalence rate"},
{id: 2156, category: "HIV/AIDS - people living with HIV/AIDS"},
{id: 2157, category: "HIV/AIDS - deaths"},
{id: 2172, category: "Distribution of family income - Gini index"},
{id: 2177, category: "Median age"},
{id: 2184, category: "Internet hosts"},
{id: 2185, category: "Investment (gross fixed)"},
{id: 2186, category: "Public debt"},
{id: 2187, category: "Current account balance"},
{id: 2188, category: "Reserves of foreign exchange and gold"},
{id: 2189, category: "Union name"},
{id: 2190, category: "Political structure"},
{id: 2191, category: "Member states"},
{id: 2192, category: "Preliminary statement"},
{id: 2193, category: "Major infectious diseases"},
{id: 2194, category: "Refugees and internally displaced persons"},
{id: 2195, category: "GDP (official exchange rate)"},
{id: 2196, category: "Trafficking in persons"},
{id: 2198, category: "Stock of direct foreign investment - at home"},
{id: 2199, category: "Stock of direct foreign investment - abroad"},
{id: 2200, category: "Market value of publicly traded shares"},
{id: 2201, category: "Total renewable water resources"},
{id: 2202, category: "Freshwater withdrawal (domestic/industrial/agricultural)"},
{id: 2203, category: "Geographic overview"},
{id: 2204, category: "Economy of the area administered by Turkish Cypriots"},
{id: 2205, category: "School life expectancy (primary to tertiary education)"},
{id: 2206, category: "Education expenditures"},
{id: 2207, category: "Central bank discount rate"},
{id: 2208, category: "Commercial bank prime lending rate"},
{id: 2211, category: "Stock of domestic credit"},
{id: 2212, category: "Urbanization"},
{id: 2213, category: "Broadcast media"},
{id: 2214, category: "Stock of narrow money"},
{id: 2215, category: "Stock of broad money"},
{id: 2216, category: "Drinking water source"},
{id: 2217, category: "Sanitation facility access"},
{id: 2218, category: "National anthem"},
{id: 2219, category: "Major urban areas - population"},
{id: 2220, category: "International law organization participation"},
{id: 2221, category: "Taxes and other revenues"},
{id: 2222, category: "Budget surplus (+) or deficit (-)"},
{id: 2223, category: "Maternal mortality rate"},
{id: 2224, category: "Children under the age of 5 years underweight"},
{id: 2225, category: "Health expenditures"},
{id: 2226, category: "Physicians density"},
{id: 2227, category: "Hospital bed density"},
{id: 2228, category: "Obesity - adult prevalence rate"},
{id: 2229, category: "Unemployment, youth ages 15-24"},
{id: 2230, category: "National symbol(s)"},
{id: 2231, category: "Shipyards and Ship Building"},
{id: 2232, category: "Electricity - production"},
{id: 2233, category: "Electricity - consumption"},
{id: 2234, category: "Electricity - exports"},
{id: 2235, category: "Electricity - imports"},
{id: 2236, category: "Electricity - installed generating capacity"},
{id: 2237, category: "Electricity - from fossil fuels"},
{id: 2238, category: "Electricity - from hydroelectric plants"},
{id: 2239, category: "Electricity - from nuclear fuels"},
{id: 2240, category: "Electricity - from other renewable sources"},
{id: 2241, category: "Crude oil - production"},
{id: 2242, category: "Crude oil - exports"},
{id: 2243, category: "Crude oil - imports"},
{id: 2244, category: "Crude oil - proved reserves"},
{id: 2245, category: "Refined petroleum products - production"},
{id: 2246, category: "Refined petroleum products - consumption"},
{id: 2247, category: "Refined petroleum products - exports"},
{id: 2248, category: "Refined petroleum products - imports"},
{id: 2249, category: "Natural gas - production"},
{id: 2250, category: "Natural gas - consumption"},
{id: 2251, category: "Natural gas - exports"},
{id: 2252, category: "Natural gas - imports"},
{id: 2253, category: "Natural gas - proved reserves"},
{id: 2254, category: "Carbon dioxide emissions from consumption of energy"},
{id: 2255, category: "Child labor - children ages 5-14"},
{id: 2256, category: "Mother's mean age at first birth"},
{id: 2257, category: "Demographic profile"},
{id: 2258, category: "Contraceptive prevalence rate"},
{id: 2259, category: "GDP - composition, by end use"},
{id: 2260, category: "Gross national saving"},
{id: 2261, category: "Dependency ratios"},
{id: 2262, category: "Abbreviated Background"},
]
