import {readFileSync, appendFileSync, writeFileSync, readdirSync} from 'fs'

const stringify = (data) => {
  const stringifyElement = (e) => {
    return e.reduce((res, e, i) => {
      if (i !== 0) {
        return res + `"${e}", ` 
      } else return res
    }, "")
  }

  return data.reduce((res, e) => {
    return res + `[${stringifyElement(e)}], `
  }, "")
}

const dataLoader = (id) => {
  const fileName = `factbook/rankorder/rawdata_${id}.txt`
  const content = readFileSync(fileName).toString()

  const rows = content.split("\r")

  const data = rows.map((e) => e.split(/\t\s*/))

  if (data.length < 10) return ""

  const output = `[${stringify(data)}]`

  return output
}

writeFileSync("data.js", `
  // This file is auto-generated, please do not edit this file.
  export default {\n`)
readdirSync('factbook/rankorder/').forEach(fileName => {
  if (/[0-9]*rank.html/.test(fileName)) {
    const id = parseInt(fileName.substr(0, 4))
    const out = dataLoader(id)
    if (out.length > 10) {
      appendFileSync("data.js", `${id}: `)
      appendFileSync("data.js", dataLoader(id))
      appendFileSync("data.js", ", \n")
    }
  }
})
appendFileSync("data.js", "}")
